### ISSUE TITLE
Add new API endpoints for IQEngine project

### ISSUE THREAD

**Issue by Nepomuceno** [IQEngine/IQEngine#132]
This proposal suggests adding several new API endpoints to the IQEngine project to enhance communication between the frontend and the backend. These endpoints will provide functionalities related to data sources and their associated metadata. 

Some background and context:

- IQEngine has a list of datasources meaning the list of places where you can get data from.
- Datasources curently are containers into a blob storage account or a local file/directory 
- The decision to use the storage accoutn name and container as datasouce id was done because it does allow you to work with datasource without the need to save them to a database and keeps compatibility with the current way of work of IQEngine while at the same time being able to unique identify a data source.
- The pagination fiels and how paginationn will be done have not been decided yet.
- All the parameters are going to be urlencoded to avoid problems with `/` and other url incompatible fileds

The proposed endpoints are as follows:

1. **GET - api/datasources/?{pagination_fields}**
   - Description: Returns a list of data source objects.
   - Parameters: None
   - Response: List of data source objects
     - ex: 
```json
[ 
   { "type": "server_blob", "name": "Cool RF recordings", "storage_account":"mystorage", "container":"mycontainer" },
   { "type": "client_blob", "name": "Private RF recordings", "storage_account":"mystorage", "container":"mycontainer", "key":"mySASkey" }
]
```
   

2. **GET - api/datasources/{id}/meta?{pagination_fields}**
   - Description: Returns the list of the latest version of all metadata files for the specified data source.
   - Parameters:
     - `id`: The identifier of the data source in the format `blob_{azure_blob_storage_account_name}_{container_name}`.
   - Response: List of the latest version of all metadata json that this datasource has

3. **GET - api/datasources/{datasource_id}/{file_path}/meta?version={version}**
   - Description: Returns the json of metadata file for the specified data source and file path.
   - Parameters:
     - `datasource_id`: The identifier of the data source in the format `blob_{azure_blob_storage_account_name}_{container_name}`.
     - `file_path`: The name of the file in the blob storage without the extension.
     - `version`: optional p[atameter to fetch one specific version
   - Response: The metadata file json

4. **GET - api/datasources/{datasource_id}/{file_path}/meta/versions?{pagination_fields}**
   - Description: Returns the list of versions for the specified metadata file of a data source.
   - Parameters:
     - `datasource_id`: The identifier of the data source in the format `blob_{azure_blob_storage_account_name}_{container_name}`.
     - `file_path`: The name of the file in the blob storage without the extension.
   - Response: List of versions of the metadata file

6. **GET - api/datasources/{datasource_id}/{file_path}/data?{data_fetching_params}**
   - Description: Returns the IQ data file for the specified data source and file path.
   - Parameters:
     - `datasource_id`: The identifier of the data source in the format `blob_{azure_blob_storage_account_name}_{container_name}`.
     - `file_path`: The name of the file in the blob storage without the extension.
     - `data_fetching_params`: have not yet being specified
   - Response: The IQ data file

7. **GET - api/datasources/{datasource_id}/{file_path}/minimap**
   - Description: Returns the JPEG minimap file for the specified data source and file path.
   - Parameters:
     - `datasource_id`: The identifier of the data source in the format `blob_{azure_blob_storage_account_name}_{container_name}`.
     - `file_path`: The name of the file in the blob storage without the extension.
   - Response: The JPEG minimap file

8. **PUT - api/datasources/{datasource_id}/{file_path}/meta**
   - Description: Updates the metadata file for the specified data source and file path.
   - Parameters:
     - `datasource_id`: The identifier of the data source in the format `blob_{azure_blob_storage_account_name}_{container_name}`.
     - `file_path`: The name of the file in the blob storage without the extension.
   - Request Body: Updated metadata file
   - Response: Success message or error if any

These new endpoints will provide efficient access to data source information, metadata, IQ data files, and minimap files, allowing for better integration and functionality within the IQEngine project.

**Comment by 777arc** [comment]
did your mega branch close out this one?

**Comment by Nepomuceno** [comment]
Yes it did
