### ISSUE TITLE
Add Admin Space

### ISSUE THREAD

**Issue by Nepomuceno** [IQEngine/IQEngine#39]
Add admin space wherte you would configure data sources that woul would have to browse.

Make sure this admin space would also allow you to setyup auth and other configurations for the app

**Comment by 777arc** [comment]
Is the idea here for those running their own instance of IQEngine, there is a way for the admin to go in and edit which blob storage accounts/containers are available on the home page?  And for auth and other configurations you are envisioning, do you think there's a way to leverage what Azure already offers (e.g. through portal or CLI) to reduce the complexity within IQEngine itself?  Thanks for the help!!

**Comment by Nepomuceno** [comment]
Excatly the idea it is that some of the functionallity that is corrent available as configuration in the environment variables can be done through an admin interface. These configurations would probably be stored in a dataabse that would them hadve its connection string setup as an environment variable.
