### ISSUE TITLE
Use recordings from url

### ISSUE THREAD

**Issue by tammojan** [IQEngine/IQEngine#645]
The Dwingeloo telescopes hosts SigMF-files at https://data.camras.nl/satellites/raw/ and various other places at the starting url.

Also, we have data sets at zenodo, e.g. [here](https://zenodo.org/record/5918529).

We would like to load these SigMF files into IQEngine without downloading them to a local computer first.

It would be cool to be able to provide a link from data.camras.nl to iqengine with the url part of the address, so that it opens the recording straight away.

**Comment by 777arc** [comment]
These are great!  Yeah I'll get them uploaded to IQEngine soon, and provide the URL format, it should look something like-

https://www.iqengine.org/api/datasources/gnuradio/iqengine/analog_FM_France.sigmf-data

**Comment by tammojan** [comment]
Do the files need to be hosted on iqengine for this to work? Of course you're welcome to copy and host them (they're all CC-BY), but my intention for this ticket was that IQEngine could take sigmf hosted at an external URL.

**Comment by 777arc** [comment]
Oh, no that doesn't work because IQEngine needs to be able to grab little portions of the datafile at a time, since it's only sending the IQ samples to your client that you're looking at.  Currently they have to be in azure blob storage, so I would have to copy them to either IQEngine's or GNU Radio's cloud storage.

**Comment by 777arc** [comment]
@tammojan FYI I uploaded those recordings to `space/Dwingeloo Radio Telescope/` within the GNU Radio tile, let me know if I should change anything

**Comment by tammojan** [comment]
This looks great, thanks!
