### ISSUE TITLE
Unable to login to iqengine.org

### ISSUE THREAD

**Issue by boonedoggle** [IQEngine/IQEngine#802]
**Describe the bug**

I'm interested in test driving the tool, but when I try to login to [https://iqengine.org](https://iqengine.org), I get the following error:

```
Selected user account does not exist in tenant 'Default Directory' and cannot access the application 'REDACTED_APPLICATION_NUMBER' in that tenant. The account needs to be added as an external user in the tenant first. Please use a different account.
```

This may not be the correct place to post this, but I could not find any contact info on the website.

**To Reproduce**
1. Go to [https://iqengine.org](https://iqengine.org)
2. Click on login
3. See error

**Expected behavior**
See above

**Screenshots**
![Screenshot](https://github.com/IQEngine/IQEngine/assets/38756277/fe3a5c34-2935-4732-8c30-f510010415b3)

**Additional context**
None

**Comment by romanziske** [comment]
This is the admin login for the public instance of IQEngine. No login is required for testing the tool. It is also possible to launch a private IQEngine instance. If you need more support check out the [IQEngine Discord](https://discord.gg/psbnXE76jj).

**Comment by 777arc** [comment]
Exactly right.  @boonedoggle the only reason to run your own server is if you want to share recordings privately within an org/company/etc

**Comment by boonedoggle** [comment]
Understood. Thanks.
