### ISSUE TITLE
Support of empty captures array

### ISSUE THREAD

**Issue by loic-fejoz** [IQEngine/IQEngine#821]
**Describe the bug**
IQEngine fails and displays errors when browsing the "local to backend" when there is a `.sigmf-meta` without any captures (present but empty list). 

**To Reproduce**
1. Deploy a local IQEngine with docker as explained in the documentation
2. Copy a `.sigmf-meta` file whose content has ` "captures": [],` 
3. Start docker
4. Browse the "Local to backend"
5. Observe the errors about "captures[0]"

**Expected behavior**
As [per specification](https://github.com/sigmf/SigMF/blob/sigmf-v1.x/sigmf-spec.md#captures-array), an empty array is valid. 
In that case,

> if there are no items in the captures array it is implied that a single capture with the core:sample_start field equal to zero

**Screenshots**

![image](https://github.com/IQEngine/IQEngine/assets/910144/d09fc9e4-2575-4b5c-a970-2adace0ae103)

**Comment by 777arc** [comment]
mmm, yep I was with Jacob when he added that blurb to the specs 6 months ago, prior to that it was sort of a grey area whether captures: [] was allowed, so yeah we'll get that fixed in IQEngine
