### ISSUE TITLE
Refresh local data

### ISSUE THREAD

**Issue by robgardien** [IQEngine/IQEngine#864]
When I refresh the local data, it doesn't reflect newly added meta and data files. When I stop and start the docker container the newly added data is visible. Is there any way to add new data without restarting the container?

**Comment by 777arc** [comment]
Yep, in your env var where you set feature flags, there's one for adding a refresh button to the top-right https://iqengine.org/docs/config-feature-flags
eg
`IQENGINE_FEATURE_FLAGS={"allowRefreshing": true, "bypassLandingPage": false, "useNewSpectrogramPage": true, "useIQEngineOutReach": true, "displayIQEngineGitHub": true, "hideInternalBranding": true}`

**Comment by 777arc** [comment]
Oh weird, you're using the latest docker image right?  When you hit refresh the backend logs should show the same activity that happens when you start the backend, where it goes through and parses each file.

**Comment by robgardien** [comment]
Yes but it is a local directory, does it work the same?

**Comment by robgardien** [comment]
It does seem to update over time, but I would like to use the refresh button for refreshing the local data

**Comment by 777arc** [comment]
When you say local data do you mean the local directory option (showed below), or using IQENGINE_BACKEND_LOCAL_FILEPATH to serve recordings local to the server?

![image](https://github.com/IQEngine/IQEngine/assets/5722532/dc2ec8a1-4b87-4747-811f-c0b2a9aecf2f)

**Comment by 777arc** [comment]
Can you ping me on Discord or email me, my contact info is on pysdr.org, we should hop on a call to work this out
